### ISSUE TITLE
调整camer距离 会影响渲染结果？

### ISSUE THREAD

**Issue by petterzhang1** [llapuras/UnityXbrShader#1]
为什么调整camera的距离会影响渲染结果？我把camera距离调整成-7就没什么效果。为什么会这样呢？

**Comment by petterzhang1** [comment]
调近距离后，图片变清晰，xbr算法就不是很好使了，因为锯齿线条会认为是直角，导致效果打折扣，这个算法的使用场景还是适合低像素的图片

**Comment by llapuras** [comment]
1. 建议把camera调成**ortho模式**，画面效果就不受camera距离影响了，这样也可以排列图片在z轴的先后顺序
2. camera距离、图片scale、像素单位的长度都会影响效果（猜测这三个因素都影响了shader处理的分辨率）
3. 在ortho模式下，图片scale、像素单位长度以及v_resolution的乘积总是**等于固定值**（原因不明）。同一品屏幕内的像素画需要按照统一像素单位长度进行绘制。
4. 这个算法适用于**纯粹**的像素sprite，用于生成某种圆润的非像素画风。
![20200702152501](https://user-images.githubusercontent.com/17641368/86329858-63d21b00-bc79-11ea-818a-380b8e2ff1bc.png)

**Comment by llapuras** [comment]
根据目前的试验得出以下数据（ortho模式下）：
|  单位像素长度   | v_resolution值  | scale |
|  ----  | ----  | ---- |
| 1  | 334 | 3 |
| 3  | 334 | 1 |
| 2  | 498 | 1 |
| 4  | 249 | 1 |
| 7  | 148 | 1 |
- 如果需要调整scale，例如scale x 2，那么v_resolution则需要除以2，保证乘积不变
- 如果单位像素长度为1，通常需要放大scale，否则根据xbr将一个像素划分为5x5进行处理的做法，最后得到的只会是一团糊糊
